export const seedDataIDD = [
    // --------> zone I <-----------------
    {
        id: 1,
        countryName_la: 'ABKHAZIA',
        countryName_en: 'ABKHAZIA',
        code: 7,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 2,
        countryName_la: 'ALASKA',
        countryName_en: 'ALASKA',
        code: 93,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 3,
        countryName_la: 'AMERICAN SAMOA',
        countryName_en: 'AMERICAN SAMOA',
        code: 684,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 4,
        countryName_la: 'ANDORRA',
        countryName_en: 'ANDORRA',
        code: 376,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 5,
        countryName_la: 'ANGOLA',
        countryName_en: 'ANGOLA',
        code: 244,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 6,
        countryName_la: 'ARMENIA',
        countryName_en: 'ARMENIA',
        code: 374,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 7,
        countryName_la: 'ARUBA',
        countryName_en: 'ARUBA',
        code: 297,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 8,
        countryName_la: 'BAHAMAS',
        countryName_en: 'BAHAMAS',
        code: 242,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 9,
        countryName_la: 'BANGLADESH',
        countryName_en: 'BANGLADESH',
        code: 880,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 10,
        countryName_la: 'BARBADOS',
        countryName_en: 'BARBADOS',
        code: 246,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 11,
        countryName_la: 'BERMUDA',
        countryName_en: 'BERMUDA',
        code: 441,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 12,
        countryName_la: 'BHUTAN',
        countryName_en: 'BHUTAN',
        code: 975,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 13,
        countryName_la: 'BOLIVIA',
        countryName_en: 'BOLIVIA',
        code: 591,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 14,
        countryName_la: 'BOTSWANA',
        countryName_en: 'BOTSWANA',
        code: 267,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 15,
        countryName_la: 'BRAZIL',
        countryName_en: 'BRAZIL',
        code: 55,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 16,
        countryName_la: 'BRITISH VIRGIN ISLANDS',
        countryName_en: 'BRITISH VIRGIN ISLANDS',
        code: 246,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 17,
        countryName_la: 'BRUNEI',
        countryName_en: 'BRUNEI',
        code: 673,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 18,
        countryName_la: 'CAMBODIA',
        countryName_en: 'CAMBODIA',
        code: 855,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 19,
        countryName_la: 'CANADA',
        countryName_en: 'CANADA',
        code: 1,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 20,
        countryName_la: 'CHINA',
        countryName_en: 'CHINA',
        code: 86,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 21,
        countryName_la: 'COLOMBIA',
        countryName_en: 'COLOMBIA',
        code: 57,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 22,
        countryName_la: 'COSTA RICA',
        countryName_en: 'COSTA RICA',
        code: 506,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 23,
        countryName_la: 'CHRISTMAS IS.',
        countryName_en: 'CHRISTMAS IS.',
        code: 86,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 24,
        countryName_la: 'COCOS IS.',
        countryName_en: 'COCOS IS.',
        code: 86,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 25,
        countryName_la: 'CZECH REP',
        countryName_en: 'CZECH REP',
        code: 357,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 26,
        countryName_la: 'DENMARK',
        countryName_en: 'DENMARK',
        code: 45,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 27,
        countryName_la: 'DOMINICAN',
        countryName_en: 'DOMINICAN',
        code: 767,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 28,
        countryName_la: 'EGYPT',
        countryName_en: 'EGYPT',
        code: 20,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 29,
        countryName_la: 'EL SALVADOR',
        countryName_en: 'EL SALVADOR',
        code: 503,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 30,
        countryName_la: 'FRANCE',
        countryName_en: 'FRANCE',
        code: 33,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 31,
        countryName_la: 'GIBRALTAR',
        countryName_en: 'GIBRALTAR',
        code: 350,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 32,
        countryName_la: 'GREECE',
        countryName_en: 'GREECE',
        code: 30,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 33,
        countryName_la: 'GUAM',
        countryName_en: 'GUAM',
        code: 671,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 34,
        countryName_la: 'GUADELOUPE',
        countryName_en: 'GUADELOUPE',
        code: 473,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 35,
        countryName_la: 'GUATEMALA',
        countryName_en: 'GUATEMALA',
        code: 502,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 36,
        countryName_la: 'HONDURAS',
        countryName_en: 'HONDURAS',
        code: 504,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 37,
        countryName_la: 'HONGKONG',
        countryName_en: 'HONGKONG',
        code: 852,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 38,
        countryName_la: 'HUNGARY',
        countryName_en: 'HUNGARY',
        code: 36,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 39,
        countryName_la: 'ICELAND',
        countryName_en: 'ICELAND',
        code: 354,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 40,
        countryName_la: 'INDIA',
        countryName_en: 'INDIA',
        code: 91,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 41,
        countryName_la: 'INDONESIA',
        countryName_en: 'INDONESIA',
        code: 62,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 42,
        countryName_la: 'IRAN',
        countryName_en: 'IRAN',
        code: 98,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 43,
        countryName_la: 'IRELAND',
        countryName_en: 'IRELAND',
        code: 353,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 44,
        countryName_la: 'ISRAEL',
        countryName_en: 'ISRAEL',
        code: 972,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 45,
        countryName_la: 'JAPAN',
        countryName_en: 'JAPAN',
        code: 81,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 46,
        countryName_la: 'JORDAN',
        countryName_en: 'JORDAN',
        code: 962,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 47,
        countryName_la: 'KENYA',
        countryName_en: 'KENYA',
        code: 254,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 48,
        countryName_la: 'KUWAIT',
        countryName_en: 'KUWAIT',
        code: 965,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 49,
        countryName_la: 'MACAU',
        countryName_en: 'MACAU',
        code: 853,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 50,
        countryName_la: 'MALAYSIA',
        countryName_en: 'MALAYSIA',
        code: 60,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 51,
        countryName_la: 'MALTA',
        countryName_en: 'MALTA',
        code: 356,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 52,
        countryName_la: 'MARTINIQUE',
        countryName_en: 'MARTINIQUE',
        code: 692,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 53,
        countryName_la: 'MAURITIUS',
        countryName_en: 'MAURITIUS',
        code: 230,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 54,
        countryName_la: 'MAYOTT',
        countryName_en: 'MAYOTT',
        code: 230,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 55,
        countryName_la: 'MEXICO',
        countryName_en: 'MEXICO',
        code: 52,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 56,
        countryName_la: 'MONGOLIA',
        countryName_en: 'MONGOLIA',
        code: 976,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 57,
        countryName_la: 'NAMIBIA',
        countryName_en: 'NAMIBIA',
        code: 264,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 58,
        countryName_la: 'NEPAL',
        countryName_en: 'NEPAL',
        code: 977,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 59,
        countryName_la: 'NEW CALEDONIA',
        countryName_en: 'NEW CALEDONIA',
        code: 687,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 60,
        countryName_la: 'NEW ZEALAND',
        countryName_en: 'NEW ZEALAND',
        code: 64,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 61,
        countryName_la: 'NIGERIA',
        countryName_en: 'NIGERIA',
        code: 234,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 62,
        countryName_la: 'NORTHERN MARINA ISLAND',
        countryName_en: 'NORTHERN MARINA ISLAND',
        code: 850,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 63,
        countryName_la: 'NORWAY',
        countryName_en: 'NORWAY',
        code: 47,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 64,
        countryName_la: 'PAKISTAN',
        countryName_en: 'PAKISTAN',
        code: 92,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 65,
        countryName_la: 'PALESTINE',
        countryName_en: 'PALESTINE',
        code: 970,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 66,
        countryName_la: 'PANAMA',
        countryName_en: 'PANAMA',
        code: 507,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 67,
        countryName_la: 'PARAGUAY',
        countryName_en: 'PARAGUAY',
        code: 595,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 68,
        countryName_la: 'PHILIPPINES',
        countryName_en: 'PHILIPPINES',
        code: 63,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 69,
        countryName_la: 'PUERTO RICO',
        countryName_en: 'PUERTO RICO',
        code: 939,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 70,
        countryName_la: 'QATAR',
        countryName_en: 'QATAR',
        code: 974,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 71,
        countryName_la: 'REUNION',
        countryName_en: 'REUNION',
        code: 262,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 72,
        countryName_la: 'ROMANIA',
        countryName_en: 'ROMANIA',
        code: 40,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 73,
        countryName_la: 'RUSSIA',
        countryName_en: 'RUSSIA',
        code: 7,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 74,
        countryName_la: 'SAUDI ARABIA',
        countryName_en: 'SAUDI ARABIA',
        code: 966,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 75,
        countryName_la: 'SAINT MARTEN',
        countryName_en: 'SAINT MARTEN',
        code: 590,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 76,
        countryName_la: 'SINGAPORE',
        countryName_en: 'SINGAPORE',
        code: 65,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 77,
        countryName_la: 'SLOVAK REP',
        countryName_en: 'SLOVAK REP',
        code: 721,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 78,
        countryName_la: 'SOUTH KOREA',
        countryName_en: 'SOUTH KOREA',
        code: 784,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 79,
        countryName_la: 'SRI LANKA',
        countryName_en: 'SRI LANKA',
        code: 784,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 80,
        countryName_la: 'SUDAN',
        countryName_en: 'SUDAN',
        code: 248,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 81,
        countryName_la: 'SWAZILAND',
        countryName_en: 'SWAZILAND',
        code: 268,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 82,
        countryName_la: 'SWEDEN',
        countryName_en: 'SWEDEN',
        code: 46,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 83,
        countryName_la: 'TAIWAN',
        countryName_en: 'TAIWAN',
        code: 886,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 84,
        countryName_la: 'TAJIKISTAN',
        countryName_en: 'TAJIKISTAN',
        code: 992,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 85,
        countryName_la: 'TELENOR CONNEXION',
        countryName_en: 'TELENOR CONNEXION',
        code: 255,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 86,
        countryName_la: 'THAILAND',
        countryName_en: 'THAILAND',
        code: 66,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 87,
        countryName_la: 'TRINIDAD & TOBAGO',
        countryName_en: 'TRINIDAD & TOBAGO',
        code: 676,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 88,
        countryName_la: 'TURKEY',
        countryName_en: 'TURKEY',
        code: 90,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 89,
        countryName_la: 'TURKMENISTAN',
        countryName_en: 'TURKMENISTAN',
        code: 993,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 90,
        countryName_la: 'UK',
        countryName_en: 'UK',
        code: 688,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 91,
        countryName_la: 'URUGUAY',
        countryName_en: 'URUGUAY',
        code: 598,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 92,
        countryName_la: 'USA',
        countryName_en: 'USA',
        code: 1,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 93,
        countryName_la: 'US VIRGIN',
        countryName_en: 'US VIRGIN',
        code: 1,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 94,
        countryName_la: 'UZBEKISTAN',
        countryName_en: 'UZBEKISTAN',
        code: 998,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 95,
        countryName_la: 'VENEZUELA',
        countryName_en: 'VENEZUELA',
        code: 58,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 96,
        countryName_la: 'VIETNAM',
        countryName_en: 'VIETNAM',
        code: 84,
        zoneId: 1,
        price_minute: 2000,
    },
    {
        id: 97,
        countryName_la: 'YEMEN',
        countryName_en: 'YEMEN',
        code: 967,
        zoneId: 1,
        price_minute: 2000,
    },

    // -------> zone II <--------
    // todo: 
    {
        id: 98,
        countryName_la: 'AFGHANISTAN',
        countryName_en: 'AFGHANISTAN',
        code: 93,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 99,
        countryName_la: 'ALBANIA',
        countryName_en: 'ALBANIA',
        code: 355,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 100,
        countryName_la: 'ALGERIA',
        countryName_en: 'ALGERIA',
        code: 213,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 101,
        countryName_la: 'ANGULILLA',
        countryName_en: 'ANGULILLA',
        code: 264,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 102,
        countryName_la: 'ANTIGUA AND BARBUDA',
        countryName_en: 'ANTIGUA AND BARBUDA',
        code: 268,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 103,
        countryName_la: 'ARGENTINA',
        countryName_en: 'ARGENTINA',
        code: 54,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 104,
        countryName_la: 'AUSTRALIA',
        countryName_en: 'AUSTRALIA',
        code: 61,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 105,
        countryName_la: 'AUSTRIA',
        countryName_en: 'AUSTRIA',
        code: 43,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 106,
        countryName_la: 'AZERBAIJANI REPUBIC',
        countryName_en: 'AZERBAIJANI REPUBIC',
        code: 994,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 107,
        countryName_la: 'BAHRAIN',
        countryName_en: 'BAHRAIN',
        code: 973,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 108,
        countryName_la: 'BELGIUM',
        countryName_en: 'BELGIUM',
        code: 32,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 109,
        countryName_la: 'BELIZE',
        countryName_en: 'BELIZE',
        code: 501,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 110,
        countryName_la: 'BENIN',
        countryName_en: 'BENIN',
        code: 229,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 111,
        countryName_la: 'BOSNIA & HERZ',
        countryName_en: 'BOSNIA & HERZ',
        code: 387,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 113,
        countryName_la: 'BULGARIA',
        countryName_en: 'BULGARIA',
        code: 359,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 114,
        countryName_la: 'BURKINA FASO',
        countryName_en: 'BURKINA FASO',
        code: 226,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 115,
        countryName_la: 'CAMEROON ',
        countryName_en: 'CAMEROON ',
        code: 237,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 116,
        countryName_la: 'CAPE VERDE',
        countryName_en: 'CAPE VERDE',
        code: 238,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 117,
        countryName_la: 'CAYMAN (ISLAND)',
        countryName_en: 'CAYMAN (ISLAND)',
        code: 236,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 118,
        countryName_la: 'CROATIA',
        countryName_en: 'CROATIA',
        code: 385,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 119,
        countryName_la: 'CYPRUS',
        countryName_en: 'CYPRUS',
        code: 357,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 120,
        countryName_la: 'DJIBOUTI',
        countryName_en: 'DJIBOUTI',
        code: 253,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 121,
        countryName_la: 'ECUADOR',
        countryName_en: 'ECUADOR',
        code: 593,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 122,
        countryName_la: 'ELSACOM  (USA)',
        countryName_en: 'ELSACOM  (USA)',
        code: 503,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 123,
        countryName_la: 'ERITREA',
        countryName_en: 'ERITREA',
        code: 291,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 124,
        countryName_la: 'ESTONIA',
        countryName_en: 'ESTONIA',
        code: 372,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 125,
        countryName_la: 'FAROE ISLAND',
        countryName_en: 'FAROE ISLAND',
        code: 500,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 126,
        countryName_la: 'FIJI',
        countryName_en: 'FIJI',
        code: 679,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 127,
        countryName_la: 'FINLAND',
        countryName_en: 'FINLAND',
        code: 358,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 128,
        countryName_la: 'FRENCH GUYANA',
        countryName_en: 'FRENCH GUYANA',
        code: 33,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 129,
        countryName_la: 'GABON',
        countryName_en: 'GABON',
        code: 241,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 130,
        countryName_la: 'GEORGIA',
        countryName_en: 'GEORGIA',
        code: 995,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 131,
        countryName_la: 'GERMANY',
        countryName_en: 'GERMANY',
        code: 49,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 132,
        countryName_la: 'GHANA',
        countryName_en: 'GHANA',
        code: 233,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 133,
        countryName_la: 'GRENADA',
        countryName_en: 'GRENADA',
        code: 473,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 134,
        countryName_la: 'GUYANA',
        countryName_en: 'GUYANA',
        code: 592,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 135,
        countryName_la: 'GUINEA',
        countryName_en: 'GUINEA',
        code: 224,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 136,
        countryName_la: 'HAITI',
        countryName_en: 'HAITI',
        code: 509,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 137,
        countryName_la: 'HAWAII',
        countryName_en: 'HAWAII',
        code: 509,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 138,
        countryName_la: 'IRAQ',
        countryName_en: 'IRAQ',
        code: 964,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 139,
        countryName_la: 'IVORY COAST',
        countryName_en: 'IVORY COAST',
        code: 225,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 140,
        countryName_la: 'JAMAICA',
        countryName_en: 'JAMAICA',
        code: 876,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 141,
        countryName_la: 'KAZAKHSTAN',
        countryName_en: 'KAZAKHSTAN',
        code: 7,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 142,
        countryName_la: 'KIRGYZSTAN',
        countryName_en: 'KIRGYZSTAN',
        code: 254,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 143,
        countryName_la: 'KOSOVO',
        countryName_en: 'KOSOVO',
        code: 383,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 144,
        countryName_la: 'LIBERIA',
        countryName_en: 'ABKHAZIA',
        code: 231,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 145,
        countryName_la: 'LIBYA',
        countryName_en: 'LIBYA',
        code: 218,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 146,
        countryName_la: 'LIECHTENSTEIN',
        countryName_en: 'LIECHTENSTEIN',
        code: 423,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 147,
        countryName_la: 'LUXEMBOURG',
        countryName_en: 'LUXEMBOURG',
        code: 352,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 148,
        countryName_la: 'MACEDONIA',
        countryName_en: 'MACEDONIA',
        code: 389,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 149,
        countryName_la: 'MALAWI',
        countryName_en: 'MALAWI',
        code: 265,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 150,
        countryName_la: 'MALI',
        countryName_en: 'MALI',
        code: 223,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 151,
        countryName_la: 'MARSHALL ISLAND',
        countryName_en: 'MARSHALL ISLAND',
        code: 356,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 152,
        countryName_la: 'MOLDOVA',
        countryName_en: 'MOLDOVA',
        code: 373,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 153,
        countryName_la: 'MONACO',
        countryName_en: 'MONACO',
        code: 377,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 154,
        countryName_la: 'MONTENEGRO',
        countryName_en: 'MONTENEGRO',
        code: 382,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 155,
        countryName_la: 'MONTSERRAT',
        countryName_en: 'MONTSERRAT',
        code: 664,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 156,
        countryName_la: 'MOROCCO',
        countryName_en: 'MOROCCO',
        code: 212,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 157,
        countryName_la: 'MOZAMBIQUE',
        countryName_en: 'MOZAMBIQUE',
        code: 258,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 158,
        countryName_la: 'MYANMAR (BURMA)',
        countryName_en: 'MYANMAR (BURMA)',
        code: 258,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 159,
        countryName_la: 'NETHERLANDS',
        countryName_en: 'NETHERLANDS',
        code: 31,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 160,
        countryName_la: 'OMAN',
        countryName_en: 'OMAN',
        code: 968,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 161,
        countryName_la: 'PALAU',
        countryName_en: 'PALAU',
        code: 680,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 162,
        countryName_la: 'PERU',
        countryName_en: 'PERU',
        code: 51,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 163,
        countryName_la: 'POLAND',
        countryName_en: 'POLAND',
        code: 48,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 164,
        countryName_la: 'PORTUGAL',
        countryName_en: 'PORTUGAL',
        code: 351,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 165,
        countryName_la: 'RWANDA',
        countryName_en: 'RWANDA',
        code: 250,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 166,
        countryName_la: 'SENEGAL',
        countryName_en: 'SENEGAL',
        code: 221,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 167,
        countryName_la: 'SERBIA',
        countryName_en: 'SERBIA',
        code: 381,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 168,
        countryName_la: 'SIERRA LEONE',
        countryName_en: 'SIERRA LEONE',
        code: 232,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 169,
        countryName_la: 'SLOVENIA',
        countryName_en: 'SLOVENIA',
        code: 386,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 170,
        countryName_la: 'SOUTH AFRICA',
        countryName_en: 'SOUTH AFRICA',
        code: 784,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 171,
        countryName_la: 'SPAIN',
        countryName_en: 'SPAIN',
        code: 784,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 172,
        countryName_la: 'ST. KITTS',
        countryName_en: 'ST. KITTS',
        code: 784,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 173,
        countryName_la: 'ST. LUCIA',
        countryName_en: 'ST. LUCIA',
        code: 784,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 174,
        countryName_la: 'ST. PIERRE & MIQUEL',
        countryName_en: 'ST. PIERRE & MIQUEL',
        code: 784,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 175,
        countryName_la: 'ST. VINCENT',
        countryName_en: 'ST. VINCENT',
        code: 784,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 176,
        countryName_la: 'SURINAME',
        countryName_en: 'SURINAME',
        code: 597,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 177,
        countryName_la: 'SYRIA',
        countryName_en: 'SYRIA',
        code: 963,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 178,
        countryName_la: 'TANZANIA',
        countryName_en: 'TANZANIA',
        code: 255,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 179,
        countryName_la: 'TOGO',
        countryName_en: 'TOGO',
        code: 78,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 180,
        countryName_la: 'TURKS AND CAICOS ISLANDS',
        countryName_en: 'TURKS AND CAICOS ISLANDS',
        code: 649,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 181,
        countryName_la: 'UGANDA',
        countryName_en: 'UGANDA',
        code: 688,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 182,
        countryName_la: 'UKRAINE',
        countryName_en: 'UKRAINE',
        code: 688,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 183,
        countryName_la: 'UNITED ARAB EMIRATES',
        countryName_en: 'UNITED ARAB EMIRATES',
        code: 971,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 184,
        countryName_la: 'ZAMBIA',
        countryName_en: 'ZAMBIA',
        code: 260,
        zoneId: 2,
        price_minute: 5000,
    },
    {
        id: 185,
        countryName_la: 'ZIMBABWE',
        countryName_en: 'ZIMBABWE',
        code: 263,
        zoneId: 2,
        price_minute: 5000,
    },

    // ---------> zone III <-----------------
    {
        id: 186,
        countryName_la: 'ASCENSION',
        countryName_en: 'ASCENSION',
        code: 297,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 187,
        countryName_la: 'BELARUS',
        countryName_en: 'BELARUS',
        code: 375,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 188,
        countryName_la: 'BURUNDI',
        countryName_en: 'BURUNDI',
        code: 257,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 189,
        countryName_la: 'CENTRAL AFRICA REP',
        countryName_en: 'CENTRAL AFRICA REP',
        code: 236,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 190,
        countryName_la: 'CHAD',
        countryName_en: 'CHAD',
        code: 235,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 191,
        countryName_la: 'CHILE',
        countryName_en: 'CHILE',
        code: 56,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 192,
        countryName_la: 'COMOROS',
        countryName_en: 'COMOROS',
        code: 269,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 193,
        countryName_la: 'CONGO ',
        countryName_en: 'CONGO ',
        code: 242,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 194,
        countryName_la: 'COOK ISLANDS',
        countryName_en: 'COOK ISLANDS',
        code: 682,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 195,
        countryName_la: 'CUBA',
        countryName_en: 'CUBA',
        code: 53,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 196,
        countryName_la: 'DIEGO GARCIA',
        countryName_en: 'DIEGO GARCIA',
        code: 45,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 197,
        countryName_la: 'EAST TIMOR',
        countryName_en: 'EAST TIMOR',
        code: 670,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 198,
        countryName_la: 'EQUATORIAL GUINEA',
        countryName_en: 'EQUATORIAL GUINEA',
        code: 240,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 199,
        countryName_la: 'FALKLAND ISLANDS',
        countryName_en: 'FALKLAND ISLANDS',
        code: 500,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 200,
        countryName_la: 'GAMBIA',
        countryName_en: 'GAMBIA',
        code: 220,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 201,
        countryName_la: 'GREENLAND',
        countryName_en: 'GREENLAND',
        code: 299,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 202,
        countryName_la: 'GUANTANAMO  CUBA',
        countryName_en: 'GUANTANAMO  CUBA',
        code: 671,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 203,
        countryName_la: 'GUINEA BISSAU',
        countryName_en: 'GUINEA BISSAU',
        code: 224,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 204,
        countryName_la: 'ITALY',
        countryName_en: 'ITALY',
        code: 39,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 205,
        countryName_la: 'LATVIA',
        countryName_en: 'LATVIA',
        code: 371,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 206,
        countryName_la: 'LITHUANIA',
        countryName_en: 'LITHUANIA',
        code: 370,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 207,
        countryName_la: 'MADAGASCAR',
        countryName_en: 'MADAGASCAR',
        code: 261,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 208,
        countryName_la: 'MALDIVES',
        countryName_en: 'MALDIVES',
        code: 960,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 209,
        countryName_la: 'MAURITANIA',
        countryName_en: 'MAURITANIA',
        code: 222,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 210,
        countryName_la: 'MICRONESIA',
        countryName_en: 'MICRONESIA',
        code: 691,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 211,
        countryName_la: 'NAURU',
        countryName_en: 'NAURU',
        code: 674,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 212,
        countryName_la: 'NICARAGUA',
        countryName_en: 'NICARAGUA',
        code: 505,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 213,
        countryName_la: 'NIGER',
        countryName_en: 'NIGER',
        code: 227,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 214,
        countryName_la: 'ONAIR ',
        countryName_en: 'ONAIR ',
        code: 968,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 215,
        countryName_la: 'PAPUA NEW GUINEA',
        countryName_en: 'PAPUA NEW GUINEA',
        code: 675,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 216,
        countryName_la: 'SAN MARINO',
        countryName_en: 'SAN MARINO',
        code: 378,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 217,
        countryName_la: 'SEYCHELLES',
        countryName_en: 'SEYCHELLES',
        code: 248,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 218,
        countryName_la: 'SOMALIA',
        countryName_en: 'SOMALIA',
        code: 252,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 219,
        countryName_la: 'SWITZERLAND',
        countryName_en: 'SWITZERLAND',
        code: 41,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 220,
        countryName_la: 'TOKELAU',
        countryName_en: 'TOKELAU',
        code: 690,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 221,
        countryName_la: 'TONGA',
        countryName_en: 'TONGA',
        code: 676,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 222,
        countryName_la: 'TUNISIA',
        countryName_en: 'TUNISIA',
        code: 216,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 223,
        countryName_la: 'TUVALU',
        countryName_en: 'TUVALU',
        code: 688,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 224,
        countryName_la: 'WALLIS AND FUTUNA',
        countryName_en: 'WALLIS AND FUTUNA',
        code: 681,
        zoneId: 3,
        price_minute: 20000,
    },
    {
        id: 225,
        countryName_la: 'WESTERN SAMOA',
        countryName_en: 'WESTERN SAMOA',
        code: 212,
        zoneId: 3,
        price_minute: 20000,
    },

    // -------> zone IV <--------
    {
        id: 226,
        countryName_la: 'ETHIOPIA',
        countryName_en: 'ETHIOPIA',
        code: 251,
        zoneId: 4,
        price_minute: 50000,
    },
    {
        id: 227,
        countryName_la: 'FRENCH POLYNESIA',
        countryName_en: 'FRENCH POLYNESIA',
        code: 689,
        zoneId: 4,
        price_minute: 50000,
    },
    {
        id: 228,
        countryName_la: 'KIRIBATI',
        countryName_en: 'KIRIBATI',
        code: 686,
        zoneId: 4,
        price_minute: 50000,
    },
    {
        id: 229,
        countryName_la: 'LEBANON',
        countryName_en: 'LEBANON',
        code: 961,
        zoneId: 4,
        price_minute: 50000,
    },
    {
        id: 230,
        countryName_la: 'LESOTHO',
        countryName_en: 'LESOTHO',
        code: 266,
        zoneId: 4,
        price_minute: 50000,
    },
    {
        id: 231,
        countryName_la: 'NIUE',
        countryName_en: 'NIUE',
        code: 683,
        zoneId: 4,
        price_minute: 50000,
    },
    {
        id: 232,
        countryName_la: 'NORFOLK ISLAND',
        countryName_en: 'NORFOLK ISLAND',
        code: 683,
        zoneId: 4,
        price_minute: 50000,
    },
    {
        id: 233,
        countryName_la: 'SAINT HELENA',
        countryName_en: 'SAINT HELENA',
        code: 590,
        zoneId: 4,
        price_minute: 50000,
    },
    {
        id: 234,
        countryName_la: 'SOLOMON ISLANDS',
        countryName_en: 'SOLOMON ISLANDS',
        code: 677,
        zoneId: 4,
        price_minute: 50000,
    },
    {
        id: 235,
        countryName_la: 'THURAYA',
        countryName_en: 'THURAYA',
        code: 66,
        zoneId: 4,
        price_minute: 50000,
    },
    {
        id: 236,
        countryName_la: 'VANUATU',
        countryName_en: 'VANUATU',
        code: 678,
        zoneId: 4,
        price_minute: 50000,
    },

    // -------> zone V <--------
    {
        id: 237,
        countryName_la: 'ELLIPSO SATELLITE SYSTEM',
        countryName_en: 'ELLIPSO SATELLITE SYSTEM',
        code: 503,
        zoneId: 5,
        price_minute: 80000,
    },
    {
        id: 238,
        countryName_la: 'INMARSAT',
        countryName_en: 'INMARSAT',
        code: 62,
        zoneId: 5,
        price_minute: 80000,
    },
    {
        id: 239,
        countryName_la: 'INTERNATIONAL NETWORKS',
        countryName_en: 'INTERNATIONAL NETWORKS',
        code: 62,
        zoneId: 5,
        price_minute: 80000,
    },
    {
        id: 240,
        countryName_la: 'IRIDIUM P SATELLITE',
        countryName_en: 'IRIDIUM P SATELLITE',
        code: 353,
        zoneId: 5,
        price_minute: 80000,
    },
    {
        id: 241,
        countryName_la: 'NORTH KOREA',
        countryName_en: 'NORTH KOREA',
        code: 850,
        zoneId: 5,
        price_minute: 80000,
    },
    
    
]